//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using CapaEntidad;

    public partial class RecursosHumanosEntities : DbContext
    {
        public RecursosHumanosEntities()
            : base("name=RecursosHumanosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargos { get; set; }
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Vacacione> Vacaciones { get; set; }
        public virtual DbSet<Licencia> Licencias { get; set; }
        public virtual DbSet<Permiso> Permisoes { get; set; }
    
        public virtual ObjectResult<BuscarEmpleado_Result> BuscarEmpleado(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BuscarEmpleado_Result>("BuscarEmpleado", nombreParameter);
        }
    
        public virtual int BorrarDepartamento(Nullable<int> codDept)
        {
            var codDeptParameter = codDept.HasValue ?
                new ObjectParameter("CodDept", codDept) :
                new ObjectParameter("CodDept", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorrarDepartamento", codDeptParameter);
        }
    
        public virtual ObjectResult<ListaEmpl_Result> ListaEmpl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaEmpl_Result>("ListaEmpl");
        }
    
        public virtual ObjectResult<ListaEmp_Result> ListaEmp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaEmp_Result>("ListaEmp");
        }
    }

   
}
